{{- if .Values.storageClasses.gp3.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClasses.gp3.name }}
  labels:
    {{- include "rook-ceph-complete.labels" . | nindent 4 }}
provisioner: ebs.csi.aws.com
parameters:
  type: {{ .Values.storageClasses.gp3.type }}
  fsType: {{ .Values.storageClasses.gp3.fsType }}
  iops: {{ .Values.storageClasses.gp3.iops | quote }}
  throughput: {{ .Values.storageClasses.gp3.throughput | quote }}
volumeBindingMode: {{ .Values.storageClasses.gp3.volumeBindingMode }}
allowVolumeExpansion: {{ .Values.storageClasses.gp3.allowVolumeExpansion }}
{{- end }}