{{- if .Values.filesystem.enabled }}
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: {{ .Values.filesystem.name }}
  namespace: {{ .Values.filesystem.namespace }}
  labels:
    {{- include "rook-ceph-complete.labels" . | nindent 4 }}
spec:
  metadataPool:
    replicated:
      size: {{ .Values.filesystem.metadataPool.replicated.size }}
  dataPools:
  {{- range .Values.filesystem.dataPools }}
  - failureDomain: {{ .failureDomain }}
    replicated:
      size: {{ .replicated.size }}
    name: {{ .name }}
  {{- end }}
  preserveFilesystemOnDelete: {{ .Values.filesystem.preserveFilesystemOnDelete }}
  metadataServer:
    activeCount: {{ .Values.filesystem.metadataServer.activeCount }}
    activeStandby: {{ .Values.filesystem.metadataServer.activeStandby }}
    resources:
      limits:
        memory: {{ .Values.filesystem.metadataServer.resources.limits.memory | quote }}
      requests:
        cpu: {{ .Values.filesystem.metadataServer.resources.requests.cpu | quote }}
        memory: {{ .Values.filesystem.metadataServer.resources.requests.memory | quote }}
    priorityClassName: {{ .Values.filesystem.metadataServer.priorityClassName }}
{{- end }}