apiVersion: v2
appVersion: v18.2.4
description: Complete Rook Ceph installation with block, filesystem, and object storage
home: https://rook.io
keywords:
- storage
- ceph
- rook
- block-storage
- filesystem
- object-storage
- s3
maintainers:
- email: admin@nvisionx.com
  name: nvisionx-team
name: rook-ceph-complete
sources:
- https://github.com/rook/rook
type: application
version: 0.1.0
